apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegetable-deployment
  namespace: namespace-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vegetable
  template:
    metadata:
      labels:
        app: vegetable
    spec:
      containers:
        - name: vegetable-container
          image: gowrish006/vegetable-app:latest
          ports:
            - containerPort: 3000
